# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arreglo',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio_venta', models.FloatField()),
                ('tamanio', models.TextField(choices=[('PEQUENIO', 'Pequenino'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=50)),
                ('canasta', models.TextField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=50)),
                ('grabado', models.TextField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=50)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=50)),
                ('numero_telefonico', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cod_arreglo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacionapp.Arreglo')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('salario', models.FloatField()),
                ('rango', models.TextField(choices=[('ADMINISTRADOR', 'Administrador'), ('EMPLEADO', 'Empleado')], max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=10)),
                ('fecha', models.DateField()),
                ('tipo_pago', models.CharField(choices=[('CREDITO', 'Credito'), ('EFECTIVO', 'Efectivo')], default='EFECTIVO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacionapp.Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacionapp.Empleado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('transaccion', models.TextField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20)),
                ('cantidad_toalla', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='Toalla',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color', models.TextField(choices=[('AMARILLO', 'Amarillo'), ('AZUL', 'Azul'), ('ROJO', 'Rojo'), ('VERDE', 'Verde'), ('NARANJA', 'Naranja'), ('MORADO', 'morado'), ('FUCSIA', 'Fucsia'), ('TURQUESA', 'Turquesa')], max_length=50)),
                ('precio_compra', models.FloatField()),
                ('tamanio', models.TextField(choices=[('PEQUENIO', 'Pequenino'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=50)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='cod_toalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacionapp.Toalla'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='cod_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacionapp.Factura'),
        ),
    ]
