# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arreglo',
            name='tamanio',
            field=models.TextField(choices=[('PEQUEÑO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rango',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('EMPLEADO', 'Empleado')], max_length=50),
        ),
    ]
