# Generated by Django 2.0 on 2018-01-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionapp', '0005_auto_20180104_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toalla',
            name='color',
            field=models.TextField(choices=[('AMARILLO', 'Amarillo'), ('AZUL', 'Azul'), ('ROJO', 'Rojo'), ('VERDE OSCURO', 'Verde oscuro'), ('VERDE CLARO', 'Verde claro'), ('NARANJA', 'Naranja'), ('MORADO', 'morado'), ('FUCSIA', 'Fucsia'), ('TURQUESA', 'Turquesa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='toalla',
            name='tamanio',
            field=models.TextField(choices=[('PEQUENIO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=50),
        ),
    ]
