# Generated by Django 2.0 on 2018-01-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionapp', '0006_auto_20180111_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toalla',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
