# Generated by Django 2.0 on 2018-01-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionapp', '0007_auto_20180111_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
