# Generated by Django 2.0 on 2018-01-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionapp', '0008_empleado_borrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cod_arreglo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facturacionapp.Arreglo'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facturacionapp.Cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facturacionapp.Empleado'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cod_toalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facturacionapp.Toalla'),
        ),
    ]
